loki:
  enabled: true
  schemaConfig:
    configs:
      - from: 2025-08-21
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  tableManager:
    retentionDeletesEnabled: true
    retentionPeriod: 168h

