loki:
  enabled: true
  config:
    schema_config:
      configs:
        - from: 2025-08-21
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
