prometheusSpec:
  scrapeClasses:
    - default: true
      name: cluster-relabeling
      relabelings:
        - sourceLabels: [__name__]
          regex: (.*)
          targetLabel: cluster
          replacement: my-cluster
          action: replace
