kubeStateMetrics:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        replacement: "minikube"
        targetLabel: cluster

prometheus:
  prometheusSpec:
    additionalScrapeConfigsSecret:
      enabled: true
      name: prometheus-scrape-configs
      key: prometheus-scrape-configs.yaml
grafana:
  enabled: true
  extraPodSpec:
    hostAliases:
      - ip: "adas.maxwin.com.tw"
        hostnames:
          - "adas.maxwin.com.tw"
  persistence:
    enabled: true
    type: pvc
    # storageClassName: grafana-sc
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection
  grafana.ini:
    server:
      root_url: http://localhost:8082
    security:
      allow_embedding: true
    auth.generic_oauth:
      enabled: true
      name: RACEV-OIDC
      allow_sign_up: true
      client_id: grafana-oauth
      client_secret: XJ5lXEBqbFNlTflgWYFwqGpjky5UbGM1
      # client_secret: DEFxRSWmtcn5OFKGBs2JpxRXQYKxuMXc
      scopes: openid email profile offline_access roles
      email_attribute_path: email
      login_attribute_path: username
      name_attribute_path: full_name
      tls_skip_verify_insecure: true
      auth_url: http://localhost:8083/realms/demo/protocol/openid-connect/auth
      token_url: http://keycloak.keycloak.svc.cluster.local/realms/demo/protocol/openid-connect/token
      api_url: http://keycloak.keycloak.svc.cluster.local/realms/demo/protocol/openid-connect/userinfo
      # auth_url: https://adas.maxwin.com.tw/apis/keycloak/realms/demo/protocol/openid-connect/auth
      # token_url: https://adas.maxwin.com.tw/apis/keycloak/realms/demo/protocol/openid-connect/token
      # api_url: https://adas.maxwin.com.tw/apis/keycloak/realms/demo/protocol/openid-connect/userinfo
      role_attribute_path: contains(resource_access."grafana-oauth".roles[*], 'admin') && 'Admin' || contains(resource_access."grafana-oauth".roles[*], 'editor') && 'Editor' || 'Viewer'
      role_attribute_strict: false
    auth:
      ## force use keycloak login page for grafana
      # disable_login_form: true
      # enable_login_token: true
      # oauth_auto_login: true
      signout_redirect_url: http://localhost:8083/realms/demo/protocol/openid-connect/logout?client_id=grafana-oauth&post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A8082

  assertNoLeakedSecrets: false
