kubeStateMetrics:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        replacement: "minikube"
        targetLabel: cluster

prometheus:
  prometheusSpec:
    additionalScrapeConfigsSecret:
      enabled: true
      name: prometheus-scrape-configs
