kubeStateMetrics:
  enabled: true

kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
  rbac:
    create: true
  releaseLabel: true
  prometheus:
    monitor:
      enabled: true
      interval: "60s"
      honorLabels: true
      relabelings:
        - sourceLabels: [__address__]
          regex: "(.*)"
          targetLabel: cluster
          replacement: "CHANGEME"
